### ISSUE TITLE
I am developing a very similar skill to this one

### ISSUE THREAD

**Issue by QW3RTZUI0P** [smartgic/mycroft-sonos-controller-skill#1]
Hey @goldyfruit,

a few days ago I stumbled over your skill while browsing on GitHub. I’m currently working on a very similar skill (https://github.com/QW3RTZUI0P/sonos-music-controller-skill) and figured that it might be unneccessary to develop two skills for the same purpose.
I installed your skill but wasn’t able to get it functioning. My skill is currently working (at least for me) and supports Spotify and Apple Music. Here’s my post on the Mycroft forum concerning my skill: https://community.mycroft.ai/t/testing-and-feedback-sonos-music-controller-skill/10313 
Maybe some of my workarounds / solutions can help you. My skill doesn’t need authentication with Spotify and handles almost everything through the speakers itself, but I tried to explain this in my README. Perhaps my issue in the SoCo package can help, too (https://github.com/SoCo/SoCo/issues/812).

Also, I’m very new to Mycroft and I’ve absolutely no experience with python and GitHub at all.

Hope I can help,
QW3RTZUI0P

**Comment by goldyfruit** [comment]
Hey @QW3RTZUI0P 

Glad to see someone with Sonos devices and Mycroft AI, thanks for reaching out and share your project! :+1: 

This skill works for me but maybe we have different setup and version of Mycroft, I'm using multiple Sonos devices with Boost, etc... and the latest Mycroft Core `dev` branch. 

I didn't published the skill yet to the community because it stills under heavy development, what was your issue?

I'm curious about the fact that you don't need authentication with Spotify, we are working with the SoCo team to bring back the music service _(Spotify, Amazon Music, etc...)_ which requires authentication (https://github.com/SoCo/SoCo/pull/763).

I have a pretty big music library based on vinyl records converted to MP3 which is why I'm having the "Music Library" part in my code.

Feel free to contribute anytime, you have pretty nice stuff in there _(`mycroft-playback-control`, iTunes, Radio)_.

**Comment by QW3RTZUI0P** [comment]
Hey, thanks for the quick answer,

I was now able to install your skill (previously I just forgot to change my language to English 😖), but I had some errors along the way:
* the pairing code given by Mycroft isn’t valid for a long period of time or is it?
* the first time I tried the skill it didn’t find the room. I don’t know whether the reason was that I spelled the room with capital letters (I was using mycroft-cli) or that I didn’t say before “discover sonos speakers” because after I had said that it worked (with lower case letters)
* the skill didn’t play the track or album I intended
* the skill threw an error when I was trying to play a track and an album. If you’d like I can give them to you.

My skill plays songs without any authentication by giving the soco speaker’s play_uri() method an URI. The URIs are service-dependant and I found them using [jishis Node HTTP API](https://github.com/jishi/node-sonos-http-api).
E.g. the URI for Spotify (at least on my system, I don’t know how the sid value changes on other systems) would be x-sonos-spotify:TRACK_ID?sid=9&flags=0&sn=19 where TRACK_ID is the URI returned by the Spotify API (e.g. “spotify:track:0tgVpDi06FyKpA1z0VMD4v”).
I’m accessing the Spotify API using the public token they give you when you visit open.spotify.com. In the source code you can search for accessToken and you’ll find one (with very limited permissions).

iTunes works similarly (URI = x-sonos-http:${id}.mp4?sid=204&flags=8224&sn=4) and the [iTunes Search API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/) doesn’t even require an access token.

Is this very workaround-y or could this be a potential solution for the SoCo music service problem?

**Comment by goldyfruit** [comment]
The way how SoCo works for Spotify is that it's looking to the Sonos Music services you registered from your Sonos App, but right now the only supported branch for this is from the PR I pasted above.

For the discovery, you need to ask the skill to find you devices and then you will know the names.

It's still under heavy development and not yet ready for production _(I'm mostly working on it everyday and commit the code)_.

Thanks for your feedback.

**Comment by goldyfruit** [comment]
Closing this issue, please feel free to reach out :+1:
